name: Compile all documentations and examples

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: Setup Python environment for sltx
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup and run sltx-install (and pu)
        run: |
          sudo apt install poppler-utils
          pip install six sltx
          echo "tx-default" | sltx docker

      - name: Compile sopra-attachments
        run: |
          cd sopra-attachments
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-attachments/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-attachments.doc.tex"

      - name: Compile sopra-base
        run: |
          cd sopra-base
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-base/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-base.doc.tex"

      - name: Compile sopra-changelog
        run: |
          cd sopra-changelog
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-changelog/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-changelog.doc.tex"

      - name: Compile sopra-documentation
        run: |
          cd sopra-documentation
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-documentation/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-documentation.doc.tex"

      - name: Compile sopra-listings
        run: |
          cd sopra-listings
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-listings/*" -print0 | xargs -0 -I '{}' cp '{}' "./"
          sltx compile --root --profile "tx-default" "sopra-listings.doc.tex"

      - name: Compile sopra-listings example
        run: |
          cd sopra-listings/examples
          cp -r ../Languages ./Languages
          sltx compile --root --profile "tx-default" "cp-listings.example.tex"

      - name: Compile sopra-models
        run: |
          cd sopra-models
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-models/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-models.doc.tex"

      - name: Compile sopra-paper
        run: |
          cd sopra-paper
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-paper/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-paper.doc.tex"

      - name: Compile sopra-requirements
        run: |
          cd sopra-requirements
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-requirements/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-requirements.doc.tex"

      - name: Compile sopra-seraphim
        run: |
          cd sopra-seraphim
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-seraphim/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-seraphim.doc.tex"

      - name: Compile sopra-ntts
        run: |
          cd sopra-ntts
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-ntts/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-ntts.doc.tex"

      - name: Compile sopra-standard
        run: |
          cd sopra-standard
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-standard/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-standard.doc.tex"

      - name: Compile sopra-tables
        run: |
          cd sopra-tables
          find "../" \( -name '*.sty' -o -name '*.cls'  -o -name 'installer.py' \) -type f -not -path "../sopra-tables/*" -print0 | xargs -0 -I '{}' cp '{}' "./" && cp -r ../sopra-listings/Languages ./Languages
          sltx compile --root --profile "tx-default" "sopra-tables.doc.tex"

      - name: Compile sopra-tables example
        run: |
          cd sopra-tables/examples
          sltx compile --root --profile "tx-default" "cp-tables.example.tex"

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f ./**/*.doc.pdf ./**/*.example.pdf
          git commit -m "Updated documentations and examples PDFs by workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "gh-pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
